# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2507c871d70b60f2188f449d87392a6ca2148868decc43fd255e66a9f20c8a1710eb7ae921e2a1b6863a72ac5dbb7675c7be779040ec1f90245eeb653f11296b

test:
  secret_key_base: bbc674dbf22ae6603992b2ee1cfe7076fcf5cb422ea83519404120312c04d3d92cd3febf84fa36ae0c15a6a289e15b84a7028d4bdcb2f265977f3eab2a720b63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
